urls.py
"""URL config for the chemical protal."""

from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls import url
from .views import (ChemicalList, ChemicalDetail, ConsumerDetail,
                    ConsumerList, CMRList, StockList, SupplierDetail,
                    DepartmentList, DepartmentView, SDSList, SDSDepartmentList,
                    ApprovalDocumentList, LocationList, LocationView,
                    StockDepartmentList, ChemicalStockList, ChemicalsMissingSDB,
                    ChemicalNumbers)


urlpatterns = [
    #########################
    # Chemical Views
    url(r'^(?P<pk>\d+)$', ChemicalDetail.as_view(), name='chemical_detail'),
    url(r'^chemicals/$', ChemicalList.as_view(), name='chemical_list'),
    url(r'^archived/$', ChemicalList.as_view(archive=True, table_heading=_(
        'Archived chemicals')), name='archived_chemicals'),
    url(r'^supplier/(?P<pk>\d+)$', SupplierDetail.as_view(),
        name='supplier_detail'),
    url(r'^department/(?P<pk>\d+)$', DepartmentView.as_view(),
        name='department_detail'),
    url(r'^departments/$', DepartmentList.as_view(), name='department_list'),
    url(r'^suppliers/$', ConsumerList.as_view(), name='supplier_list'),
    url(r'^cmr/$', CMRList.as_view(), name='cmr_list'),
    url(r'^sds/department/(?P<pk>\d+)$', SDSDepartmentList.as_view(),
        name='sds_department_list'),
    url(r'^sds/$', SDSList.as_view(), name='sds_list'),
    url(r'^approval/$', ApprovalDocumentList.as_view(), name='approval_list'),
    #########################
    # SHE Views
    url(r'^missingsdb/$', ChemicalsMissingSDB.as_view(),
        name='chemical_missing_sdb'),
    url(r'numbers/$', ChemicalNumbers.as_view(), name='chemical_numbers'),
    #########################
    # Stock Views
    url(r'^stocks/department/(?P<pk>\d+)$', StockDepartmentList.as_view(),
        name='stock_department_list'),
    url(r'^stocks/$', StockList.as_view(), name='stock_list'),
    url(r'^chemical/(?P<chem_id>\d+)/department/(?P<dep_id>\d+)$',
        ConsumerDetail.as_view(), name='chemical_department'),
    url(r'^locations/$', LocationList.as_view(), name='location_list'),
    url(r'^location/(?P<pk>\d+)$', LocationView.as_view(),
        name='stock_location_list'),
    url(r'^chemicalstocks/$', ChemicalStockList.as_view(),
        name='chemical_stock_list'),
    #########################
    # Generic Views
    url(r'^$', RedirectView.as_view(url=reverse_lazy('chemical_list'),
                                    permanent=True), name='home'),
]

models/chemical.py
"""Models that are related to a chemical."""

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField
from django.utils.translation import ugettext_lazy as _
from polymorphic.models import PolymorphicModel


class HPhrase(models.Model):
    """Simple class for storing H phrases of a chemical. This also contains
    information about Seveso relevance and CMR value."""

    CMR = (
        (1, _('CMR Category 1A/1B')),
        (2, _('CMR Category 2')),
        (9, _('Not CMR relevant')),
    )
    name = models.CharField(max_length=40, verbose_name=_("H-Phrase"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))
    seveso_relevant = models.BooleanField(default=False,
                                          verbose_name=_("Seveso Relevant"))
    cmr = models.IntegerField(default=9, choices=CMR, verbose_name=_("CMR"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("H-Phrase")
        verbose_name_plural = _("H-Phrases")


class PPhrase(models.Model):
    """Simple class for storing P phrases of a chemical."""

    name = models.CharField(max_length=40, verbose_name=_("P-Phrase"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("P-Phrase")
        verbose_name_plural = _("P-Phrases")


class RPhrase(models.Model):
    """Simple class for storing R phrases of a chemical."""

    name = models.CharField(max_length=40, verbose_name=_("R-Phrase"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("R-Phrase")
        verbose_name_plural = _("R-Phrases")


class SevesoCategory(models.Model):
    """Class for the Seveso category of a chemical."""

    name = models.CharField(max_length=40, verbose_name=_("Seveso Category"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name', )
        app_label = "chemicals"
        verbose_name = _("Seveso Category")
        verbose_name_plural = _("Seveso Categories")


class StorageClass(models.Model):
    """Class for the storage class of a chemical."""

    name = models.CharField(max_length=40, verbose_name=_("Storage Class"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("Storage Class")
        verbose_name_plural = _("Storage Classes")


class WGK(models.Model):
    """Simple class for storing the WGK of a chemical."""

    name = models.CharField(max_length=20, verbose_name=_("WGK"))
    description = models.CharField(max_length=400, blank=True, null=True,
                                   verbose_name=_("Description"))

    def __unicode__(self):
        return "%s - %s" % (self.name, self.description)

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("WGK")
        verbose_name_plural = _("WGKs")


class RiskIndication(models.Model):
    """Simple class for the risk class of a chemical."""

    name = models.CharField(max_length=100, verbose_name=_("Risk"))

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("Risk Indication")
        verbose_name_plural = _("Risk Indications")


class Chemical(models.Model):
    """The Chemical is the heart of this application."""
    SIGNALS = (('d', _('danger')), ('w', _('warning')), ('n', _('no signal')),)

    comment = models.TextField(verbose_name=_("Comment"), blank=True,
                               default='')
    article = models.CharField(max_length=100, blank=True, null=True,
                               verbose_name=_("Article Number"))
    registration_number = models.CharField(
        max_length=200, blank=True, null=True,
        verbose_name=_("Registration Number")
    )
    cas = models.CharField(max_length=200, blank=True, null=True,
                           verbose_name=_("CAS"))
    einecs = models.CharField(max_length=200, blank=True, null=True,
                              verbose_name=_("EINECS"))
    signal = models.CharField(max_length=1, choices=SIGNALS, blank=True,
                              default='', verbose_name=_("Signal"))

    # Boolean switches
    region_de = models.BooleanField(default=True, verbose_name=_("Region D"))
    region_be = models.BooleanField(default=False, verbose_name=_("Region B"))
    archive = models.BooleanField(default=False, verbose_name=_("Archive"))
    needed = models.BooleanField(default=False,
                                 verbose_name=_("Permanently Needed"))
    preparation = models.BooleanField(default=False,
                                      verbose_name=_("Preparation"))
    components_registered = models.BooleanField(
        default=False, verbose_name=_("Components Registered"))
    reach_vo = models.BooleanField(
        default=False, verbose_name=_("Listed in annex XIV REACH regulation"))

    # Many to one relations
    wgk = models.ForeignKey(WGK, default=1, verbose_name=_("WGK"))
    storage_class = models.ForeignKey(StorageClass, default=1,
                                      verbose_name=_("Storage Class"))

    # Many to many relations
    seveso_categories = models.ManyToManyField(
        SevesoCategory, blank=True, verbose_name=_("Seveso Categories"))
    rphrases = models.ManyToManyField(RPhrase, blank=True,
                                      verbose_name=_("R-Phrases"))
    pphrases = models.ManyToManyField(PPhrase, blank=True,
                                      verbose_name=_("P-Phrases"))
    pictograms = models.ManyToManyField('Pictogram', blank=True,
                                        verbose_name=_("Pictogram"))

    # Many to many relations with dedicated relation table
    risks = models.ManyToManyField(RiskIndication, through='Risk', blank=True,
                                   verbose_name=_("Risk Indication"))
    hphrases = models.ManyToManyField(HPhrase, through='HPhraseRelation',
                                      blank=True, verbose_name=_("H-Phrases"))
    locations = models.ManyToManyField('Location', through='Stock', blank=True,
                                       verbose_name=_("Locations"))
    departments = models.ManyToManyField('Department', through='Consumer',
                                         blank=True,
                                         verbose_name=_("Departments"))
    suppliers = models.ManyToManyField('Supplier', through='Consumer',
                                       blank=True,
                                       verbose_name=_("Suppliers"))

    @property
    def cmr1(self):
        if self.hphrases.all().aggregate(models.Min('cmr'))['cmr__min'] == 1:
            return True
        else:
            return False

    @property
    def cmr2(self):
        if self.hphrases.all().aggregate(models.Min('cmr'))['cmr__min'] == 2:
            return True
        else:
            return False

    @property
    def seveso_relevant(self):
        return self.hphrases.filter(seveso_relevant=True).exists()

    def get_approval_documents(self):
        return self.document_set.filter(doctype="f")

    def get_info_documents(self):
        return self.document_set.filter(doctype="i")

    def __unicode__(self):
        return self.name.name

    def get_absolute_url(self):
        return reverse('chemical_detail', kwargs={'pk': self.pk})

    class Meta:
        app_label = "chemicals"
        verbose_name = _("Chemical")
        verbose_name_plural = _("Chemicals")


class ChemicalName(PolymorphicModel):
    """This only contains the name of the chemicals and synonyms."""
    name = models.CharField(max_length=200, verbose_name=_("Chemical"),
                            db_index=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        app_label = "chemicals"
        verbose_name = _("ChemicalName")
        verbose_name_plural = _("ChemicalNames")


class Identifier(ChemicalName):
    """Class for storing the name of a chemical."""
    chemical = models.OneToOneField(Chemical, default=1, related_name="name",
                                    verbose_name=_("Chemical"))

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = "chemicals"
        verbose_name = _("Name")
        verbose_name_plural = _("Name")


class Synonym(ChemicalName):
    """Simple Class for storing synonyms of chemicals."""
    chemical = models.ForeignKey(Chemical, default=1, related_name="synonyms",
                                 verbose_name=_("Chemical"))

    def __unicode__(self):
        return self.name

    class Meta:
        app_label = "chemicals"
        verbose_name = _("Synonym")
        verbose_name_plural = _("Synonyms")

templates/chemicals/base.html
{% extends "base.html" %}
{% load i18n sekizai_tags %}
{% load static from staticfiles %}
{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "chemicals/css/base.css" %}">
{% endblock %}

{% block top_menu %}
    <ul class="nav navbar-nav">
        <li><a class="navbar-button" href="{% url "sds_list" %}">{% trans "MSDS" %}</a></li>
        <li><a class="navbar-button" href="{% url "chemical_list" %}">{% trans "Chemicals" %}</a></li>
        <li><a class="navbar-button" href="{% url "stock_list" %}">{% trans "Chemical Stock" %}</a></li>
        <li class="dropdown">
            <a id="chem_dd1" class="navbar-button" role="button" data-toggle="dropdown" href="#">
                {% trans "More Views" %}
                <span class="caret"></span>
            </a>
            <ul id="chem_menu1" class="dropdown-menu" role="menu" aria-labelledby="chem_dd1">
                <li class="navheading"> {% trans "Chemical Views" %}</li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Chemicals" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "supplier_list" %}/?lid=1">{% trans "Suppliers" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "department_list" %}">{% trans "Departments" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "cmr_list" %}">{% trans "CMR" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "archived_chemicals" %}">{% trans "Archive" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "sds_list" %}">{% trans "MSDS" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "approval_list" %}">{% trans "Approval Documents" %}</a></li>
                {% if perms.chemicals.view_she %}
                    <li class="navheading"> {% trans "SHE Views" %}</li>
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "H-Phrases" %}</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "chemical_missing_sdb" %}">{% trans "Chemicals without SDS" %}</a></li>
                    <!--
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Seveso-View Departments" %}</a></li>
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Seveso-View" %}</a></li>
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Seveso-View Listed Chemicals" %}</a></li>
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Checklists" %}</a></li>
                    -->
                    <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Tox Oekotox" %}</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "chemical_numbers" %}">{% trans "Chemical Numbers" %}</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "admin:chemicals_chemical_changelist" %}"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                        {% trans "Administration" %}</a></li>
                {% endif %}
                <li class="navheading"> {% trans "Chemical Stock Views" %}</li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "stock_list" %}">{% trans "Departments" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "location_list" %}">{% trans "Stock Locations" %}</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "chemical_stock_list" %}">{% trans "Chemicals" %}</a></li>
                <!--
                <li role="presentation" class="disabled"><a role="menuitem" tabindex="-1" href="{% url "chemical_list" %}">{% trans "Checklists" %}</a></li>
                -->
            </ul>
        </li>
    </ul>
{% endblock %}
{% block base_content %}
    <div id="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <button type=button" class="close" data-dismiss="alert" aria-lagel="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    </div>
    <div id="content">
        {% block chemical_content %}
        {% endblock %}
    </div>
    {% addtoblock "js" %}
        <script type="text/javascript"
            src="{% static "chemicals/js/chemicals.js" %}">
        </script>
    {% endaddtoblock %}
{% endblock %}

templates/chemicals/chemical_detail.html
{% extends "chemicals/base.html" %}
{% load i18n chemical_tags %}
{% load render_table from django_tables2 %}

{% block chemical_content %}
    <h1>
        {{ chemical.name }}
        {% if perms.chemicals.change_chemical %}
        <a role="button" class="close" aria-label="Edit"
            href="{% url 'admin:chemicals_chemical_change' chemical.id %}">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        </a>
        {% endif %}
    </h1>
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg-6">
                    <table style="width:100%;">
                        <tr>
                            <th>{% trans "Article Number" %}</th>
                            <td>{{ chemical.article }}</td>
                        </tr><tr>
                            <th>{% trans "Registration Number" %}</th>
                            <td>{{ chemical.registration_number }}</td>
                        </tr>
                    </table>
                </div>
                <div class="col-lg-6">
                    <table style="width:100%;">
                        <tr>
                            <th>{% trans "CAS" %}</th>
                            <td>{{ chemical.cas }}</td>
                        </tr><tr>
                            <th>{% trans "EINECS" %}</th>
                            <td>{{ chemical.einecs }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <br><strong>{% trans "Synonyms" %}</strong>
            <ul class="list-inline">
                {% for obj in chemical.synonyms.all %}
                <li>{{ obj.name }}</li>
                {% endfor %}
            </ul>
            <br><strong>{% trans "Comment" %}</strong>
            <div class="well well-sm">
                {{ chemical.comment }}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.preparation|yesno:" checked," }}> {% trans "Preparation" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.needed|yesno:" checked," }}> {% trans "Always needed" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.components_registered|yesno:" checked," }}> {% trans "Components registered" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.archive|yesno:" checked," }}> {% trans "Archived" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.reach_vo|yesno:" checked," }}>
                <span {% if chemical.preparation %} class="text-muted"{% endif %}>
                {% trans "Listed in annex XIV REACH regulation" %}
                </span>
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.cmr1|yesno:" checked," }}> {% trans "CMR Category 1A/1B" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.cmr2|yesno:" checked," }}> {% trans "CMR Category 2" %}
            </label></div>
            <div class="checkbox"><label>
                <input type="checkbox" disabled{{ chemical.seveso_relevant|yesno:" checked," }}> {% trans "Seveso relevant" %}
            </label></div>
        </div>
    </div>
    <p>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#classification" data-toggle="tab">{% trans "Classification" %}</a></li>
            <li><a href="#department" data-toggle="tab">{% trans "Department / Supplier" %}</a></li>
            <li><a href="#sds" data-toggle="tab">{% trans "SDS / Document" %}</a></li>
            <li><a href="#reach" data-toggle="tab">REACH</a></li>
            <!-- li><a href="#checklist" data-toggle="tab">{% trans "Checklist" %}</a></li -->
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="classification">
                <br>
                <h3>{% trans "CLP" %}</h3>
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Pictogram" %}</th><th>{% trans "Description" %}</th></tr>
                            {% for obj in chemical.pictograms.all %}
                            <tr><td><img src="{{ obj.image.url }}" alt="{{ obj.name }}"></td><td>{{ obj.name }}</td></tr>
                            {% endfor %}
                        </table>
                        <p><b>{% trans "Signal" %}:</b> {{ chemical.signal|show_signal }}</p><br>
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Storage Class" %}</th><th>{% trans "Description" %}</th></tr>
                            <tr><td>{{ chemical.storage_class.name }}</td><td>{{ chemical.storage_class.description }}</td></tr>
                        </table>
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Water Hazard Classification" %}</th><th>{% trans "Description" %}</th></tr>
                            <tr><td>{{ chemical.wgk.name }}</td><td>{{ chemical.wgk.description }}</td></tr>
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "ID" %}</th><th>{% trans "H-Phrase" %}</th></tr>
                            {% for obj in chemical.hphrases.all %}
                            <tr><td>{{ obj.name }}</td><td>{{ obj.description }}</td></tr>
                            {% endfor %}
                        </table>
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Supplier" %}</th><th>{% trans "Tox" %}</th><th>{% trans "Oekotox" %}</th></tr>
                            {% for obj in chemical.toxdata_set.all %}
                            <tr><td>{{ obj.supplier.name }}</td><td>{{ obj.tox|yesno }}</td><td>{{ obj.oekotox|yesno }}</td></tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <h3 class="de-emphasize">{% trans "Chemical Directive" %}</h3>
                <div class="row de-emphasize">
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Risk" %}</th><th>{% trans "Info" %}</th></tr>
                            {% for obj in chemical.risk_set.all %}
                            <tr><td>{{ obj.riskindication.name }}</td><td>{{ obj.info }}</td></tr>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "ID" %}</th><th>{% trans "R-Phrase" %}</th></tr>
                            {% for obj in chemical.rphrases.all %}
                            <tr><td>{{ obj.name }}</td><td>{{ obj.description }}</td></tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="department">
                <h3>{% trans "Department" %}</h3>
                <div class="table-responsive">
                    {% render_table table "chemicals/table.html" %}
                </div>
            </div>
            <div class="tab-pane fade" id="sds">
                <div class="row">
                    <div class="col-lg-6">
                        <h3>{% trans "Safety Data Sheets" %}</h3>
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Published on" %}</th><th>{% trans "Supplier" %}</th><th>{% trans "Language" %}</th><th>{% trans "SDS" %}</th></tr>
                            {% for obj in chemical.safetydatasheet_set.all %}
                            <tr><td>{{ obj.issue_date }}</td><td>{{ obj.supplier.name }}</td><td>{{ obj.country_code|language_name_local }}</td><td>
                                    <a href="{{ obj.file.url }}" target="_blank">
                                        <span class="glyphicon glyphicon-file"></span> {{ obj.file.name }}</a>
                            </td></tr>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <h3>{% trans "Extended Safety Data Sheets" %}</h3>
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Published on" %}</th><th>{% trans "Supplier" %}</th><th>{% trans "Language" %}</th><th>{% trans "eSDS" %}</th></tr>
                            {% for obj in chemical.extendedsafetydatasheet_set.all %}
                            <tr><td>{{ obj.issue_date }}</td><td>{{ obj.supplier.name }}</td><td>{{ obj.country_code|language_name_local }}</td><td>
                                    <a href="{{ obj.file.url }}" target="_blank">
                                        <span class="glyphicon glyphicon-file"></span> {{ obj.file.name }}</a>
                            </td></tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <h3>{% trans "Documents" %}</h3>
                    </div>
                    <div class="col-lg-6">
                        <h3>{% trans "General documents" %}</h3>
                    </div>
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Created on" %}</th><th>{% trans "Plant" %}</th><th>{% trans "Approval" %}</th></tr>
                            {% for obj in chemical.get_approval_documents.all %}
                            <tr><td>{{ obj.created }}</td><td>{{ obj.plant }}</td><td>
                                    <a href="{{ obj.file.url }}" target="_blank">
                                        <span class="glyphicon glyphicon-file"></span> {{ obj.file.name }}</a>
                            </td></tr>
                            {% endfor %}
                        </table>

                    </div>
                    <div class="col-lg-6">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Created on" %}</th><th>{% trans "Info" %}</th></tr>
                            {% for obj in chemical.get_info_documents.all %}
                            <tr><td>{{ obj.created }}</td><td>
                                    <a href="{{ obj.file.url }}" target="_blank">
                                        <span class="glyphicon glyphicon-file"></span> {{ obj.file.name }}</a>
                            </td></tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="reach">
                <br>
                <div class="row">
                    <div class="col-lg-9">
                        <p><b>{% trans "Registration Number" %}:</b> {{ chemical.registration_number }}</p>
                        <b>{% trans "Info" %}</b>
                        <div class="well well-sm">
                            {{ chemical.reachinformation_set.first.description }}
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <table class="table table-striped table-bordered table-condensed">
                            <tr><th>{% trans "Language" %}</th><th>{% trans "Document" %}</th></tr>
                            {% for obj in chemical.reachdocument_set.all %}
                            <tr><td>{{ obj.country_code|language_name_local }}</td><td><a type="button" class="btn btn-warning btn-sm" href="{{ obj.file.url }}" target="_blank">
                                        <span class="glyphicon glyphicon-file"></span> {{ obj.file.extension|upper }}</a>
                            </td></tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <!-- 
            <div class="tab-pane fade" id="checklist">
            </div>
            -->
        </div>
    </p>
{% endblock %}